#!/usr/bin/env python3
"""ALFlowLyzer realtime supervisor.

This script starts:
- tcpdump capture into rotating pcap files
- ALFlowLyzer chunk processing that appends into a live CSV

It intentionally does not start any detector process.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import signal
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path


STOP_REQUESTED = False
TCPDUMP_PROCESS: subprocess.Popen[str] | None = None


def log_stderr(message: str) -> None:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}] {message}", file=sys.stderr)


def handle_signal(_signum, _frame):
    global STOP_REQUESTED
    STOP_REQUESTED = True
    stop_process(TCPDUMP_PROCESS)


def stop_process(process: subprocess.Popen[str] | None) -> None:
    if process is None:
        return
    try:
        if process.poll() is None:
            process.terminate()
            try:
                process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                process.kill()
    except Exception:
        pass


def clean_work_dir(work_dir: Path) -> None:
    """Remove files generated by previous runs under the work directory."""
    for subdir_name in ["pcap", "chunks", "tmp"]:
        subdir = work_dir / subdir_name
        if not subdir.exists():
            continue
        for entry in subdir.iterdir():
            try:
                if entry.is_dir() and not entry.is_symlink():
                    shutil.rmtree(entry)
                else:
                    entry.unlink()
            except Exception as exc:
                log_stderr(f"[WARN] Failed to remove {entry}: {exc}")

    live_csv = work_dir / "alflow_live.csv"
    if live_csv.exists():
        try:
            live_csv.unlink()
        except Exception as exc:
            log_stderr(f"[WARN] Failed to remove {live_csv}: {exc}")


def build_arg_parser() -> argparse.ArgumentParser:
    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parent
    venv_alflow = repo_root / ".venv" / "bin" / "alflowlyzer"

    parser = argparse.ArgumentParser(description="ALFlowLyzer realtime supervisor")
    parser.add_argument("--iface", default="eth0", help="Capture interface")
    parser.add_argument("--chunk-seconds", type=int, default=5, help="Pcap chunk duration")
    parser.add_argument("--work-dir", default="/tmp/alflow_rt", help="Working directory")
    parser.add_argument("--base-config", default=str(repo_root / "tunnel" / "alflowlyzer_config.json"), help="ALFlowLyzer base config")
    parser.add_argument("--alflow-cmd", default=str(venv_alflow), help="ALFlowLyzer executable")
    parser.add_argument("--bpf", default="(udp port 53 or tcp port 53)", help="tcpdump BPF filter")
    return parser


def process_chunk(
    pcap_file: Path,
    work_dir: Path,
    base_config: Path,
    alflow_cmd: str,
    live_csv: Path,
) -> None:
    stem = pcap_file.stem
    out_csv = work_dir / "chunks" / f"{stem}.csv"
    cfg_json = work_dir / "tmp" / f"config_{stem}.json"
    err_log = work_dir / "tmp" / f"alflow_{stem}.log"

    cfg = json.loads(base_config.read_text())
    cfg["pcap_file_address"] = str(pcap_file)
    cfg["output_file_address"] = str(out_csv)

    # Lower buffering for near-real-time processing.
    cfg["feature_extractor_min_flows"] = 10
    cfg["writer_min_rows"] = 10
    cfg["check_flows_ending_min_flows"] = 50
    cfg["capturer_updating_flows_min_value"] = 50
    cfg["read_packets_count_value_log_info"] = 1000

    cfg_json.write_text(json.dumps(cfg, indent=2))

    with err_log.open("w", encoding="utf-8") as err_handle:
        completed = subprocess.run([alflow_cmd, "-c", str(cfg_json)], stdout=err_handle, stderr=subprocess.STDOUT)

    if completed.returncode != 0:
        log_stderr(f"[ERR] ALFlowLyzer failed on {pcap_file.name}")
        log_stderr(f"[ERR] config: {cfg_json}")
        log_stderr(f"[ERR] log: {err_log}")
        try:
            tail = err_log.read_text(encoding="utf-8", errors="ignore").splitlines()[-40:]
            for line in tail:
                log_stderr(line)
        except Exception:
            pass
        return

    if out_csv.exists() and out_csv.stat().st_size > 0:
        if not live_csv.exists() or live_csv.stat().st_size == 0:
            live_csv.write_text(out_csv.read_text())
        else:
            out_lines = out_csv.read_text().splitlines()
            if len(out_lines) > 1:
                with live_csv.open("a", encoding="utf-8") as live_handle:
                    live_handle.write("\n".join(out_lines[1:]))
                    live_handle.write("\n")
        log_stderr(f"[OK] processed {pcap_file.name} -> {out_csv.name}")
    else:
        log_stderr(f"[SKIP] no rows from {pcap_file.name}")


def main() -> int:
    global TCPDUMP_PROCESS, STOP_REQUESTED

    parser = build_arg_parser()
    args = parser.parse_args()

    signal.signal(signal.SIGINT, handle_signal)
    signal.signal(signal.SIGTERM, handle_signal)

    work_dir = Path(args.work_dir)
    base_config = Path(args.base_config)
    live_csv = work_dir / "alflow_live.csv"
    pcap_dir = work_dir / "pcap"
    chunks_dir = work_dir / "chunks"
    tmp_dir = work_dir / "tmp"

    if not base_config.exists():
        log_stderr(f"Base config not found: {base_config}")
        return 1

    work_dir.mkdir(parents=True, exist_ok=True)
    pcap_dir.mkdir(parents=True, exist_ok=True)
    chunks_dir.mkdir(parents=True, exist_ok=True)
    tmp_dir.mkdir(parents=True, exist_ok=True)

    try:
        os.chmod(work_dir, 0o777)
        os.chmod(pcap_dir, 0o777)
        os.chmod(chunks_dir, 0o777)
        os.chmod(tmp_dir, 0o777)
    except Exception:
        pass

    log_stderr("Cleaning temporary files from previous run...")
    clean_work_dir(work_dir)

    live_csv.touch()

    tcpdump_cmd = "tcpdump"
    if not shutil_which(tcpdump_cmd):
        log_stderr("tcpdump not found in PATH")
        return 1

    if not Path(args.alflow_cmd).exists() and not shutil_which(args.alflow_cmd):
        log_stderr(f"ALFlowLyzer executable not found: {args.alflow_cmd}")
        log_stderr("If you are using sudo, point --alflow-cmd at the venv entrypoint or install ALFlowLyzer into the same venv.")
        return 1

    log_stderr("Starting ALFlowLyzer realtime pipeline...")

    TCPDUMP_PROCESS = subprocess.Popen(
        [
            tcpdump_cmd,
            "-i",
            args.iface,
            "-nn",
            "-s0",
            "-G",
            str(args.chunk_seconds),
            "-w",
            str(pcap_dir / "dns_%Y%m%d_%H%M%S.pcap"),
            args.bpf,
        ]
    )

    time.sleep(1)
    if TCPDUMP_PROCESS.poll() is not None:
        log_stderr("tcpdump exited immediately. Check interface name, privileges, and BPF filter.")
        return 1

    seen: set[Path] = set()

    while not STOP_REQUESTED:
        pcaps = sorted(pcap_dir.glob("dns_*.pcap"))
        if len(pcaps) > 1:
            for pcap_file in pcaps[:-1]:
                if STOP_REQUESTED:
                    break
                if pcap_file in seen:
                    continue
                process_chunk(pcap_file, work_dir, base_config, args.alflow_cmd, live_csv)
                seen.add(pcap_file)
        time.sleep(1)

    return 0


def shutil_which(cmd: str) -> str | None:
    for path_dir in os.environ.get("PATH", "").split(os.pathsep):
        candidate = Path(path_dir) / cmd
        if candidate.exists() and os.access(candidate, os.X_OK):
            return str(candidate)
    return None


if __name__ == "__main__":
    raise SystemExit(main())
